# Generated by Django 6.0.5 on 2026-05-25 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecOdejda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('upper', 'Верхняя одежда'), ('shoes', 'Обувь'), ('gloves', 'Перчатки'), ('head', 'Головной убор'), ('other', 'Прочее')], max_length=20, verbose_name='Тип')),
                ('size', models.CharField(max_length=10, verbose_name='Размер')),
                ('norm_days', models.IntegerField(verbose_name='Срок носки по нормативу (дней)')),
                ('quantity_in_stock', models.IntegerField(default=0, verbose_name='Количество на складе')),
            ],
            options={
                'verbose_name': 'Единица спецодежды',
                'verbose_name_plural': 'Спецодежда',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='IssuedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('wear_level', models.IntegerField(default=100, verbose_name='Остаточный ресурс (%)')),
                ('status', models.CharField(choices=[('issued', 'Выдана'), ('worn_out', 'Изношена'), ('written_off', 'Списана')], default='issued', max_length=20, verbose_name='Статус')),
                ('spec_odejda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.specodejda', verbose_name='Спецодежда')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Запись о выдаче',
                'verbose_name_plural': 'Журнал выдачи',
            },
        ),
    ]
