# Generated by Django 6.0.5 on 2026-05-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueditem',
            name='wear_level',
            field=models.IntegerField(default=0, verbose_name='Износ (%)'),
        ),
    ]
